<?php
/**
 * ClanChest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Clash Royale API
 *
 * This API description is based on the api provided by http://cr-api.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cr-api@manutrix.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * ClanChest Class Doc Comment
 *
 * @category    Class */
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ClanChest implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ClanChest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'clan_chest_crowns' => 'int',
        'clan_chest_crowns_percent' => 'float',
        'clan_chest_crowns_required' => 'int'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'clan_chest_crowns' => 'clanChestCrowns',
        'clan_chest_crowns_percent' => 'clanChestCrownsPercent',
        'clan_chest_crowns_required' => 'clanChestCrownsRequired'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'clan_chest_crowns' => 'setClanChestCrowns',
        'clan_chest_crowns_percent' => 'setClanChestCrownsPercent',
        'clan_chest_crowns_required' => 'setClanChestCrownsRequired'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'clan_chest_crowns' => 'getClanChestCrowns',
        'clan_chest_crowns_percent' => 'getClanChestCrownsPercent',
        'clan_chest_crowns_required' => 'getClanChestCrownsRequired'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['clan_chest_crowns'] = isset($data['clan_chest_crowns']) ? $data['clan_chest_crowns'] : null;
        $this->container['clan_chest_crowns_percent'] = isset($data['clan_chest_crowns_percent']) ? $data['clan_chest_crowns_percent'] : null;
        $this->container['clan_chest_crowns_required'] = isset($data['clan_chest_crowns_required']) ? $data['clan_chest_crowns_required'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets clan_chest_crowns
     * @return int
     */
    public function getClanChestCrowns()
    {
        return $this->container['clan_chest_crowns'];
    }

    /**
     * Sets clan_chest_crowns
     * @param int $clan_chest_crowns
     * @return $this
     */
    public function setClanChestCrowns($clan_chest_crowns)
    {
        $this->container['clan_chest_crowns'] = $clan_chest_crowns;

        return $this;
    }

    /**
     * Gets clan_chest_crowns_percent
     * @return float
     */
    public function getClanChestCrownsPercent()
    {
        return $this->container['clan_chest_crowns_percent'];
    }

    /**
     * Sets clan_chest_crowns_percent
     * @param float $clan_chest_crowns_percent
     * @return $this
     */
    public function setClanChestCrownsPercent($clan_chest_crowns_percent)
    {
        $this->container['clan_chest_crowns_percent'] = $clan_chest_crowns_percent;

        return $this;
    }

    /**
     * Gets clan_chest_crowns_required
     * @return int
     */
    public function getClanChestCrownsRequired()
    {
        return $this->container['clan_chest_crowns_required'];
    }

    /**
     * Sets clan_chest_crowns_required
     * @param int $clan_chest_crowns_required
     * @return $this
     */
    public function setClanChestCrownsRequired($clan_chest_crowns_required)
    {
        $this->container['clan_chest_crowns_required'] = $clan_chest_crowns_required;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}
