<?php
/**
 * StatsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Clash Royale API
 *
 * This API description is based on the api provided by http://cr-api.com
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cr-api@manutrix.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StatsTest Class Doc Comment
 *
 * @category    Class */
// * @description Stats
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StatsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Stats"
     */
    public function testStats()
    {

    }

    /**
     * Test attribute "legendary_trophies"
     */
    public function testPropertyLegendaryTrophies()
    {

    }

    /**
     * Test attribute "tournament_cards_won"
     */
    public function testPropertyTournamentCardsWon()
    {

    }

    /**
     * Test attribute "max_trophies"
     */
    public function testPropertyMaxTrophies()
    {

    }

    /**
     * Test attribute "three_crown_wins"
     */
    public function testPropertyThreeCrownWins()
    {

    }

    /**
     * Test attribute "cards_found"
     */
    public function testPropertyCardsFound()
    {

    }

    /**
     * Test attribute "total_donations"
     */
    public function testPropertyTotalDonations()
    {

    }

    /**
     * Test attribute "challenge_max_wins"
     */
    public function testPropertyChallengeMaxWins()
    {

    }

    /**
     * Test attribute "challenge_cards_won"
     */
    public function testPropertyChallengeCardsWon()
    {

    }

    /**
     * Test attribute "level"
     */
    public function testPropertyLevel()
    {

    }

    /**
     * Test attribute "favorite_card"
     */
    public function testPropertyFavoriteCard()
    {

    }

}
